services:
  - type: web
    name: cryptopredict-backend
    runtime: python
    buildCommand: "pip install -r backened/requirements.txt"
    startCommand: "gunicorn --chdir backened app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 5001
